== 注释映射
=== 为什么使用注释?
一度长时间来Dozer都是使用XML进行配置。直到五年前还是XML高度兴盛的时期，之后才有了更加优雅明显的好选择。直到Java5带来了注释，新的产业届接受了基于领域定义语言的配置方式。DSL类似形式的映射API直到5.3.2 Dozer提供了注释之后提供了支持。

最明显使用注释的原因是避免了使用重复的属性和方法名称在你的映射代码中。注释可以放到映射属性上从而减少代码数量。然而仍然有一些使用注释的场景需要避免或者是不能够被使用。其中包括如下所示：

* 你映射的一些类，不在你的控制之下，但是是通过类库进行提示;
* 映射相当复杂，需要很多配置信息;

你第一场景中你将映射 JAXB 生成的实体或者是第三方的DTOs， 你没有可能将注释放到其中。在第二个场景中需要放置过多行的注释或者是为确定重复实体名称使用孤立的映射代码。过度的注释beans将会给阅读和理解带来问题。

=== 用法
*警告:* Dozer中的注释支持是实验性的不支持复杂的使用场景。然而它确是在XML或者是API之前最简单的实现。

这个主意是简单的。你可以直接放置 @Mapping 注释在属性的 getter 方法上。 如果 Dozer 发现该注释将会增加双向的映射。这意味着一次放注释将会创建两个类型的映射。类型转化将被自动选择(例如：字符串-长整型)。全局的自定义转化器也能被解析。
注释只有在采用通配符的情况才能生效。(默认被激活) 如下的例子展示了注释的使用。

[source,java,prettyprint]
----
public class SourceBean {

    private Long id;

    private String name;

    @Mapping("binaryData")
    private String data;

    @Mapping("pk")
    public Long getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }
}              
----

[source,java,prettyprint]
----
public class TargetBean {

    private String pk;

    private String name;

    private String binaryData;

    public void setPk(String pk) {
        this.pk = pk;
    }

    public void setName(String name) {
        this.name = name;
    }
}              
----

使用 Dozer 映射给定的 beans 将会导致三个属性都会被映射。name属性将会通过命名转化规则进行映射。id属性将会被传递到"pk"。data域将会被移动到 "binaryData". 不必担心 _private_ 修饰符; 它将自动被处理。

当前 Dozer 只提供了一个注释， 但是以后的版本中将会添加更多的支持。因而你可以采用混合的方式来使用各种不同的类型来达到所需要的效果: Xml, API 和 注释。
