== 集合和数组映射
Dozer 在集合类型中进行自动映射和自动进行任何类型转化。源集合中的每个元素都映射到目标对象的一个元素中。
Hints 被用来定义在目标集合中将创建什么类型的对象。如下类的集合类型将被Dozer自动处理: (这些都是双向的)

* List 到 List
* List 到 Array
* Array 到 Array
* Set 到 Set
* Set 到 Array
* Set 到 List

=== 使用 Hints 进行集合映射
如果你使用JDK1.5的泛型或数组，不需要使用 Hint，因为这些类型能够被 Dozer 自动检测到。
但是你如果没有使用泛型或数组，需要将一个集合数组转化到一个不同类型对象的集合数组，需要定义
Hint 让Dozer 知道你想在目标列表中创建的数据类型。如果 Hint 没有被定义在目标域中，则目标集合中将使用和源集合中元素一样的数据类型。

[source,xml,prettyprint]
----
<!-- converting TheFirstSubClass List to TheFirstSubClassPrime List -->
<field>
    <a>hintList</a>
    <b>hintList</b>
    <b-hint>com.github.dozermapper.core.vo.TheFirstSubClassPrime</b-hint>
</field>
----

下面是对数组，集合，列表的映射逻辑的总结。以及给出了当hints没有被定义时候出现的问题。

* List to List
* ** 目标 Hint 强制需要: NO
** 目标 Hint 允许: YES
** 如果目标hint没有被定义: 目标列表中将使用和源列表中一样的数据类型
** 如果 hint 被定义: 目标列表将包含匹配目标hint类型一样的对象

* Array to List
* ** 目标 Hint 强制需要: NO
** 目标 Hint 允许: YES
** 如果目标hint没有被定义: 目标列表中将使用和源列表中一样的数据类型
** 如果 hint 被定义: 目标列表将包含匹配目标hint类型一样的对象

* List to Array
* ** 目标 Hint 强制需要: NO
** 目标 Hint 允许: YES
** 如果目标hint没有被定义: 目标数组中将使用和数组中定义一样的数据类型 
** 如果 hint 被定义: 目标列表将包含匹配目标hint类型一样的对象(仅仅是对象数组)

* Array to Array
* ** 目标 Hint 强制需要: NO
** 目标 Hint 允许: YES
** 如果目标hint没有被定义: 目标数组中将使用和源列表中一样的数据类型
** 如果 hint 被定义: 目标列表将包含匹配目标hint类型一样的对象(仅仅是对象数组)

* Set to Set
* ** 目标 Hint 强制需要: NO
** 目标 Hint 允许: YES
** 如果目标hint没有被定义: 目标列表中将使用和源列表中一样的数据类型
** 如果 hint 被定义: 目标列表将包含匹配目标hint类型一样的对象

* Array to Set
* ** 目标 Hint 强制需要: NO
** 目标 Hint 允许: YES
** 如果目标hint没有被定义: 目标列表中将使用和源列表中一样的数据类型
** 如果 hint 被定义: 目标列表将包含匹配目标hint类型一样的对象

* Set to Array
* ** 目标 Hint 强制需要: NO
** 目标 Hint 允许: YES
** 如果目标hint没有被定义: 目标数组中将使用和数组中定义一样的数据类型 
** 如果 hint 被定义: 目标列表将包含匹配目标hint类型一样的对象(仅仅是对象数组)

* List to Set
* ** 目标 Hint 强制需要: NO
** 目标 Hint 允许: YES
** 如果目标hint没有被定义: 目标列表中将使用和源列表中一样的数据类型
** 如果 hint 被定义: 目标列表将包含匹配目标hint类型一样的对象

* Set to List
* ** 目标 Hint 强制需要: NO
** 目标 Hint 允许: YES
** 如果目标hint没有被定义: 目标列表中将使用和源列表中一样的数据类型
** 如果 hint 被定义: 目标列表将包含匹配目标hint类型一样的对象

== 使用 JDK 1.5 泛型进行集合映射
当使用JDK1.5泛型时候，Hints是不需要。将一个集合/数组转化成另外一个类型的集合/数组， dozer 能够在运行时检测到参数化的类型。

[source,java,prettyprint]
----
public class UserGroup {

  private Set<User> users;

  public Set<User> getUsers() {
    return users;
  }

  public void setUsers(Set<User> aUsers) {
    users = aUsers;
  }

}
public class UserGroupPrime {

  private List<UserPrime> users;

  public List<UserPrime> getUsers() {
    return users;
  }

  public void setUsers(List<UserPrime> aUsers) {
    users = aUsers;
  }

}
----

=== 对象数组到列表 (双向)
当转化一个对象数组到一个列表，缺省情况下目标列表将包含有和源数组一样的数据类型。

[source,xml,prettyprint]
----
<!-- changing an Integer [] to List and back again -->
<field>
    <a>arrayForLists</a>
    <b>listForArray</b>
</field>
----

使用hint来处理数据类型转化。当 hint 被定义时，目标列表将包含字符串元素，而不是数字。

[source,xml,prettyprint]
----
<!-- changing an Integer [] to List and back again -->
<field>
    <a>arrayForLists</a>
    <b>listForArray</b>
    <b-hint>java.lang.String</b-hint>
</field>
----

=== 原生数组到原生数组(双向)
当转化一个对象数组到一个数组，缺省情况下目标列表将包含有和源数组一样的数据类型。

[source,xml,prettyprint]
----
<!-- converting int[] to int [] by name only -->
<field>
    <a>anArray</a>
    <b>theMappedArray</b>
</field>
----

=== 累计和非累积的集合映射(双向)
当你需要映射的一个类已经被初始化，dozer可以使用新增或更新对象到你的列表中。
如果你的列表或者集合已经包含对象在其中，dozer将检查映射的列表、集合或数组，和调用 contains() 方法来决定是否需要新增或者修改。
这是通过使用域标签中的relationship-type 属性来决定的。默认是累计的。relationship-type 可以被定义在域映射、类映射或者全局配置级别中。

全局配置级别....

[source,xml,prettyprint]
----
<mappings>
    <configuration>
        <relationship-type>non-cumulative</relationship-type>
    </configuration>
</mappings>
----

类映射级别....

[source,xml,prettyprint]
----
<mappings>
    <mapping relationship-type="non-cumulative">
        <class-a>com.github.dozermapper.core.vo.TestObject</class-a>
        <class-b>com.github.dozermapper.core.vo.TestObjectPrime</class-b>
        <field>
            <a>someList</a>
            <b>someList</b>
        </field>
    </mapping>
</mappings>
----

域映射级别....

[source,xml,prettyprint]
----
<!-- 对象总是被添加到已经存在的列表中 -->
<field relationship-type="cumulative">
    <a>hintList</a>
    <b>hintList</b>
    <a-hint>com.github.dozermapper.core.vo.TheFirstSubClass</a-hint>
    <b-hint>com.github.dozermapper.core.vo.TheFirstSubClassPrime</b-hint>
</field>

<!-- 如果列表中存在对象将被更新，如果不存在将被添加 -->
<field relationship-type="non-cumulative">
    <a>unequalNamedList</a>
    <b>theMappedUnequallyNamedList</b>
</field>
----

*Note:* 如果你没有定义自定义的 _equals()_ 和 _hashCode()_ 方法，非累计选项将不能正常工作，因为Dozer将错误的判断对象的相等和依赖于JDK产生的对象ids。
缺省情况下一个类的两个实例将被区别开来，将不会导致更新。

=== 移除无效的元素
无效的元素指的是存在于目标集合而不存在于源集合中。
Dozer 将删除无效元素通过调用底层的目标集合中的remove方法在实际无效元素上。它将不会清空所有。
dozer使用contains方法来检测结果中是否包含无效元素。缺省的设定是 false。

[source,xml,prettyprint]
----
<!-- orphan objects will always be removed from an existing destination List -->
<field remove-orphans="true">
    <a>srcList</a>
    <b>destList</b>
</field>
----
