== 自定义转化器
自定义转化器应用于自定义于两个对象之间的映射。在配置块中，你可以添加一些XML来告诉 Dozer在确定的A类和B类之间使用自定义转化器。
当在A类和B类组合中使用了自定义转化器，Dozer 将会用自定义转化器进行数据映射而不是原来的标准映射逻辑。

你的自定义转化器必须实现 `org.dozer.CustomConverter` 接口从而让 Dozer 能够接受它。或者将会抛出异常。

自定义转化器在多个映射文件之间共享。这意味着你可以在一个映射文件中定义之后，它将作用于所有的其他映射文件中针对匹配类型A和类型B的模式。
在如下的例子中，Dozer使用一个匹配源头和目标的自定义转化器定义，它将调用自定义转化器类而不是传统的映射。

[source,xml,prettyprint]
----
<?xml version="1.0" encoding="UTF-8"?>
<mappings xmlns="http://dozermapper.github.io/schema/bean-mapping"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://dozermapper.github.io/schema/bean-mapping http://dozermapper.github.io/schema/bean-mapping.xsd">
    <configuration>
        <custom-converters>
            <!-- these are always bi-directional -->
            <converter type="com.github.dozermapper.core.converters.TestCustomConverter">
                <class-a>com.github.dozermapper.core.vo.CustomDoubleObject</class-a>
                <class-b>java.lang.Double</class-b>
            </converter>
            <!-- You are responsible for mapping everything between
           ClassA and ClassB -->
            <converter type="com.github.dozermapper.core.converters.TestCustomHashMapConverter">
                <class-a>
          com.github.dozermapper.core.vo.TestCustomConverterHashMapObject
        </class-a>
                <class-b>
          com.github.dozermapper.core.vo.TestCustomConverterHashMapPrimeObject
        </class-b>
            </converter>
        </custom-converters>
    </configuration>
</mappings>
----

自定义转化器可以被定义在独立的属性级别。在如下的例子中，Dozer将调用自定义转化器来进行属性映射。

[source,xml,prettyprint]
----
<mapping>
    <class-a>com.github.dozermapper.core.vo.SimpleObj</class-a>
    <class-b>com.github.dozermapper.core.vo.SimpleObjPrime2</class-b>
    <field custom-converter="com.github.dozermapper.core.converters.StringAppendCustomConverter">
        <a>field1</a>
        <b>field1Prime</b>
    </field>
</mapping>
----

自定义转化器实例可以在独立属性级别复用。在如下的例子中，Dozer 将调用自定义转化器进行属性映射。

[source,xml,prettyprint]
----
<mapping>
    <class-a>com.github.dozermapper.core.vo.SimpleObj</class-a>
    <class-b>com.github.dozermapper.core.vo.SimpleObjPrime2</class-b>
    <field custom-converter-id="CustomConverterWithId">
        <a>field1</a>
        <b>field1Prime</b>
    </field>
</mapping>
----

自定义转化器实例可以通过使用`DozerBeanMapperBuilder#withCustomConverter(..)` 方法在`Mapper`对象上进行配置。

[source,xml,prettyprint]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans default-lazy-init="false">
    <bean id="com.github.dozermapper.core.Mapper" class="com.github.dozermapper.core.DozerBeanMapper">
        <property name="mappingFiles">
            <list>
                <value>dozerBeanMapping.xml</value>
                <value>injectedCustomConverter.xml</value>
            </list>
        </property>
        <property name="customConvertersWithId">
            <map>
                <entry key="CustomConverterWithId" ref="configurableConverterBeanInstance1" />
                <entry key="CustomConverterWithId2" ref="configurableConverterBeanInstance2" />
            </map>
        </property>
    </bean>
</beans>
----

自定义转化器实现样例:

*注意:* 自定义转化器当源对象为null时候也会被调用，因此你需要显示的处理null值在你的自定义转化器实现中。

[source,java,prettyprint]
----
import com.github.dozermapper.core.CustomConverter;
import com.github.dozermapper.core.MappingException;

public class TestCustomConverter implements CustomConverter {

    @Override
    public Object convert(Object existingDestinationFieldValue, Object sourceFieldValue, Class<?> destinationClass, Class<?> sourceClass) {
        if (sourceFieldValue == null) {
            return null;
        }

        CustomDoubleObject dest;
        if (source instanceof Double) {
            // check to see if the object already exists
            if (destination == null) {
                dest = new CustomDoubleObject();
            } else {
                dest = (CustomDoubleObject)destination;
            }

            dest.setTheDouble(((Double)source).doubleValue());

            return dest;
        } else if (source instanceof CustomDoubleObject) {
            double sourceObj = ((CustomDoubleObject)source).getTheDouble();
            return new Double(sourceObj);
        } else {
            throw new MappingException("Converter TestCustomConverter "
                                       + "used incorrectly. Arguments passed in were:"
                                       + destination
                                       + " and "
                                       + source);
        }
    }
}
----

如果你需要在它们被dozer使用之前做一些处理，可以将自定义转化器注入到`Mapper`中。

[source,xml,prettyprint]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans default-lazy-init="false">
    <bean id="com.github.dozermapper.core.Mapper" class="com.github.dozermapper.core.DozerBeanMapper">
        <property name="mappingFiles">
            <list>
                <value>dozerBeanMapping.xml</value>
                <value>injectedCustomConverter.xml</value>
            </list>
        </property>
        <property name="customConverters">
            <list>
                <ref bean="customConverterTest" />
            </list>
        </property>
    </bean>
    <!-- custom converter -->
    <bean id="customConverterTest" class="com.github.dozermapper.core.converters.InjectedCustomConverter">
        <property name="injectedName">
            <value>injectedName</value>
        </property>
    </bean>
</beans>
----

=== 支持数组类型
你可以针对数组类型定义一个自定义转化器。例如，你想使用一个自定义转化器来将数组对象和字符串进行映射，你将使用如下的映射注释。Dozer 通常使用 `ClassLoader.loadClass()` 当解析映射文件的时候。针对数组，java通常希望类名称为如下的格式:`[Lorg.dozer.vo.SimpleObj`;

[source,xml,prettyprint]
----
<converter type="com.github.dozermapper.core.converters.StringAppendCustomConverter">
    <class-a>[Lcom.github.dozermapper.core.vo.SimpleObj;</class-a>
    <class-b>java.lang.String</class-b>
</converter>
----

=== 支持原生类型
你可以定义一个自定义转化器针对原生类型。只需要在定义自定义转化器映射的时候使用原生类型的包装类。如下的例子中， Dozer 将使用自定义转化器在SomeObject和int原生类型之间。
注意 Dozer 也将使用该转化器作用于 `SomeObject` 和 `Integer` 的包装类型。

[source,xml,prettyprint]
----
<converter type="somePackage.SomeCustomConverter">
    <class-a>somePackage.SomeObject</class-a>
    <class-b>java.lang.Integer</class-b>
</converter>
----

=== 配置自定义转化器
你可以在定义一个自定义转化器时候，在映射中配置参数。在这个例子中你将实现
`ConfigurableCustomConverter` 接口而不是通常的 `CustomConverter` 类。
可配置的转化器包含额外的运行时参数来提供的属性。参数通过使用`custom-converter-param`属性进行提供。

[source,xml,prettyprint]
----
<mapping>
    <class-a>com.github.dozermapper.core.vo.BeanA</class-a>
    <class-b>com.github.dozermapper.core.vo.BeanB</class-b>
    <field custom-converter="com.github.dozermapper.core.converters.MathOperationConverter" custom-converter-param="+">
        <a>amount</a>
        <b>amount</b>
    </field>
</mapping>
----

可配置的自定义转化器只有当你在许多例子中有相似的行为的时候通过参数化的方法使用。
从而简化组合使用自定义转化器子类的数目。

[source,java,prettyprint]
----
import com.github.dozermapper.core.ConfigurableCustomConverter;
import com.github.dozermapper.core.MappingException;

public class MathOperationConverter implements ConfigurableCustomConverter {

    private String parameter;

    @Override
    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    @Override
    public Object convert(Object existingDestinationFieldValue, Object sourceFieldValue, Class<?> destinationClass, Class<?> sourceClass) {
        Integer source = (Integer)sourceFieldValue;
        Integer destination = (Integer)existingDestinationFieldValue;

        if ("+".equals(parameter)) {
            return destination.intValue + source.intValue();
        }

        if ("-".equals(parameter)) {
            return destination.intValue - source.intValue();
        }

        throw new MappingException("Converter MathOperationConverter "
                                   + "used incorrectly. Arguments passed in were:"
                                   + destination
                                   + ", "
                                   + source
                                   + " and "
                                   + parameter);
    }
}
----

=== 新的自定义转化器API
然而上面所提供的大量灵活的自定义转化器API都是使用相当低级的抽象。这将导致转化器很难以被理解和在其他Dozer映射注入方式下重用。
然而通常在相同的场景中相同的转化逻辑将被应用而不是整个映射框架级别的。
新版本的 Dozer 提供了新的干净 API 来处理自定义转化器，将给你提供更加明显的API来处理特定的执行流程中的控制部分 。
如下的例子中展示一个简单例子，新版本的API来使用转化器。

[source,java,prettyprint]
----
import com.github.dozermapper.core.DozerConverter;

public class NewDozerConverter extends DozerConverter<String, Boolean> {

    public NewDozerConverter() {
        super(String.class, Boolean.class);
    }

    @Override
    public Boolean convertTo(String source, Boolean destination) {
        if ("yes".equals(source)) {
            return Boolean.TRUE;
        } else if ("no".equals(source)) {
            return Boolean.FALSE;
        }
        throw new IllegalStateException("Unknown value!");
    }

    @Override
    public String convertFrom(Boolean source, String destination) {
        if (Boolean.TRUE.equals(source)) {
            return "yes";
        } else if (Boolean.FALSE.equals(source)) {
            return "no";
        }
        throw new IllegalStateException("Unknown value!");
    }
}
----

注意 支持Java 5 泛型，因此你不需要像之前一样转化原始对象到目标对象。

=== 数据结构转化
在一些场景中需要执行程序化数据结构的转化，例如复制每个列表中的奇数号元素作为map中的键，偶数号元素作为值。
在这个例子中仍然在定义结构转化中需要依赖于通常的Dozer对每个值映射。
为了这个目的，可能需要使用`MapperAware`接口，这将在自定义转化器中注入当前的映射实例。

[source,java,prettyprint]
----
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.github.dozermapper.core.DozerConverter;
import com.github.dozermapper.core.Mapper;
import com.github.dozermapper.core.MapperAware;

public class Converter extends DozerConverter<List, Map> implements MapperAware {

    private Mapper mapper;

    public Converter() {
        super(List.class, Map.class);
    }

    @Override
    public void setMapper(Mapper mapper) {
        this.mapper = mapper;
    }

    @Override
    public Map convertTo(List source, Map destination) {
        Map originalToMapped = new HashMap();
        for (Source item : source) {
            Target mappedItem = mapper.map(item, Target.class);

            originalToMapped.put(item, mappedItem);
        }
        return originalToMapped;
    }

    @Override
    public List convertFrom(Map source, List destination) {
        throw new IllegalStateException("Not implemented");
    }
}
----
