== 自定义对象工厂类
你可以配置 Dozer 在映射过程中使用自定义的对象工厂来创建新的目标对象实例。缺省情况下 Dozer 只用该目标对象中的默认构造器创建新的实例。这对于大多数情况下是足够的，但是如果你如果需要更多灵活性，你可以通过定义自己的对象工厂来构造数据对象。

你的自定义对象工厂必须实现 `org.dozer.BeanFactory` 接口。缺省情况下 Dozer 映射引擎将会使用目标对象的类名作为bean id参数调用改工厂类。

[source,java,prettyprint]
----
public interface BeanFactory {
  public Object createBean(Object source, Class sourceClass, 
      String targetBeanId, BeanContainer beanContainer);
}
----

接下来，在你的 Dozer 映射文件中你只需要定义一个
`bean-factory` xml 属性在你需要使用自定义工厂中的映射中。

在下面的例子中, `SampleCustomBeanFactory` 将会被用作创建任何`InsideTestObjectPrime` 数据对象的实例。

[source,xml,prettyprint]
----
<mapping>
    <class-a>com.example.vo.InsideTestObject</class-a>
    <class-b bean-factory="com.example.factories.SomeCustomBeanFactory">
        com.example.vo.InsideTestObjectPrime
    </class-b>
</mapping>
----

如果你的工厂将会基于不同的id来查找java beans 而不是类名，你可以定义 `factory-bean-id` xml 属性。在运行时，定义的属性 `factory-bean-id` 将会替代类名传递到工厂类中。

[source,xml,prettyprint]
----
<mapping>
    <class-a>com.example.vo.InsideTestObject</class-a>
    <class-b bean-factory="com.example.factories.SomeCustomBeanFactory" factory-bean-id="someBeanLookupId">
        com.example.vo.InsideTestObjectPrime
    </class-b>
</mapping>
----

=== 定义缺省的工厂类
可供选择的情况下，bean工厂可以被定义到缺省的配置部分在任何的 Dozer 映射文件中。缺省的工厂将被使用到在该文件中的所有映射。

[source,xml,prettyprint]
----
<configuration>
    <stop-on-errors>true</stop-on-errors>
    <wildcard>true</wildcard>
    <bean-factory>com.example.factories.SomeDefaultBeanFactory
  </bean-factory>
</configuration>
----

Bean 工厂也可以被定义到类级别。定义的工厂将作用于 `class-a` 和 `class-b`之间。

[source,xml,prettyprint]
----
<mapping bean-factory="com.example.factories.SomeCustomBeanFactory">
    <class-a>com.example.vo.TestObject</class-a>
    <class-b>com.example.vo.TestObjectPrime</class-b>
</mapping>
----

=== Spring bean 工厂的注入
Bean 工厂可以通过spring或者类似的控制反转技术进行注入。

[source,xml,prettyprint]
----
<beans>
    <bean id="com.github.dozermapper.core.Mapper" class="com.github.dozermapper.core.DozerBeanMapper">
        <property name="mappingFiles">
            <list>
                <value>dozerBeanMapping.xml</value>
            </list>
        </property>
        <property name="factories">
            <map>
                <!-- the key matches the name of the factory in the
             dozerBeanMapping.xml file -->
                <entry key="com.github.dozermapper.core.factories.SampleCustomBeanFactory">
                    <ref bean="sampleCustomBeanFactory" />
                </entry>
                <!-- more factories can be supplied with additional
             entry's -->
            </map>
        </property>
    </bean>
    <bean id="sampleCustomBeanFactory" class="com.github.dozermapper.core.factories.SampleCustomBeanFactory" />
</beans>
----

通过定义你的工厂为spring beans，你可以将他们注入到 `Mapper` 实例中。
