:dozer-version: 6.5.0-SNAPSHOT

== 常见问题
=== 常用
* link:#dataobject-support[什么类型的数据对象被支持?]
* link:#datatype-conversions[Dozer会进行自动数据类型转化吗?]
* link:#auto-property-name[Dozer会自动对属性名称匹配的域进行映射吗?]
* link:#is-recursive[Dozer 是递归的吗?]
* link:#are-getset-invoked[getter和 setter方法在域进行映射的时候会被调用吗?]
* link:#are-collections-supported[集合和数组类型被支持吗?]
* link:#are-maps-supported[映射类型对象被支持吗?]
* link:#is-inheritance-supported[抽象类，继承和接口映射是否被支持?]
* link:#is-spring-supported[Dozer能够通过spring进行配置吗?]
* link:#what-type-custom-mapping[什么类型的数据映射需要自定义xml的映射文件?]
* link:#matching-prop-names[如果我的源和目标对象包含所有匹配的属性名称，我还需要任何xml映射定义吗?]
* link:#is-bidirectional[针对需要xml映射文件定义的映射是否是双向的，或者还需要我定义第二个xml文件进行另外一个方向的映射?]
* link:#how-xml-loaded[自定义xml映射文件是如何加载的?]
* link:#how-to-load-file[我如何加载一个不在classpath中的映射文件?]
* link:#dozer-debug[我如何知道Dozer是否已经正确的初始化和加载我的xml映射文件的?]
* link:#dozer-perf[Dozer是如何工作的?]
* link:#jdk-support[那个版本的JDK被支持?]
* link:#maven-repo[Dozer在maven仓库吗?]
* link:#good-environment[Dozer对环境友好吗?]

=== 高级
* link:#custom-converters[我如何实现在两个数据类型中进行自定义的映射逻辑，Dozer在进行映射的时候如何调用自定义的逻辑?]
* link:#deep-mapping[我是否可以映射一个域到另外一个在目标对象n层深的域?]
* link:#mult-fields-to-single-field[我如何映射多个域到一个独立的域?]
* link:#infinite-loop[如果我映射的数据对象包含双向的关系，其是否会导致一个死循环和堆栈溢出的错误?]
* link:#index-mapping[我如何映射一个集合中的对象到一个域?]
* link:#complex-to-map[我如何映射复杂的队形到哈希列表和反向处理?]
* link:#is-accessible[我如何映射不包含对应getter/setter方法的域?]
* link:#private-constructors[我的一些数据对象不包含公开的构造函数，Dozer是否支持这种案例?]
* link:#enum-support[Dozer 支持 JDK 1.5的枚举类型吗?]
* link:#xmlbeans-jaxb[Dozer 支持 XMLBeans和JAXB生成的数据对象吗?]
* link:#eclipse-plugin[是否包含支持Dozer的 Eclipse 插件或可视化编辑器?]
* link:#collection-hints[当映射集合的时候，我如何告诉Dozer我需要映射的目标集合的数据类型?]
* link:#bypass-null[我如何告诉Dozer忽略映射 null 或空的字符串值?]

=== 提示，小技巧和建议
* link:#encapsulation[我是否需要封装对象间复制数据的逻辑?]
* link:#dozer-unit-tests[我是否需要为使用Dozer进行处理的映射逻辑编写单元测试?]
* link:#config-as-singleton[Dozer映射器是否需要配置成单例?]
* link:#component-mappings[包含一个大的xml映射文件或包含多个小的映射文件，哪种方式好?]
* link:#debugging-dozer[调试Dozer的最好方式是什么?]
* link:#global-config[设定全局配置的最好方式是什么?]
* link:#submitting-support-request[提交bug，功能请求或补丁的最佳方式是什么?]

=== 回答
[[dataobject-support]]
=== 什么类型的数据对象被支持?
Dozer 使用反射获取数据对象的属性，因此其被设计为在数据对象中包含有getter和setter方法的域属性可以工作。
例如，一个数据对象包含一个域，名称为message,应该包含 getMessage 和 setMessage 方法。
数据对象不包含这种模式的也能够被支持，但是这需要一个自定义的映射定义。
对于不正确使用的数据对象，你可以告诉Dozer直接操作域（包括私有属性）和/或显式的定义get/set方法来使用。

[[datatype-conversions]]
=== Dozer会进行自动数据类型转化吗?
是的。大多数场景都是开箱即用的。这包括原生类型、java包装对象、Number的子类型、日期、日历、集合、数组、列表和复杂的类型。

[[auto-property-name]]
=== Dozer会自动对属性名称匹配的域进行映射吗?
是的。所有的匹配属性名称相同的域都会隐式被映射。
这是一个较为传统的用法，你可以通过设定wilcard="false"来关闭这种行为。

[[is-recursive]]
=== Dozer 是递归的吗?
是的。Dozer递归的映射整个对象图中的所有域。

[[are-getset-invoked]]
=== getter和 setter方法在域进行映射的时候会被调用吗?
是的。你可以在你的任何映射中忽略该缺省的行为通过显式的设定 is-accessible="true"。如果 is-accessible被定义，域(包括私有域)将被直接操作，
getter/setter 方法将被忽略。不建议你设定 is-accessible="true", 除非你要处理不正规的数据对象，其不包含任何 getter 或 setter方法。

[[are-collections-supported]]
=== 集合和数组类型被支持吗?
是的。Dozer 自动映射集合类型，自动进行类型转化。

[[are-maps-supported]]
=== 映射类型对象被支持吗?
是的。所有的java 映射数据类型都支持，此外自定义映射数据类型也支持。

[[is-inheritance-supported]]
=== 抽象类，继承和接口映射是否被支持?
是的。

[[is-spring-supported]]
=== Dozer能够通过spring进行配置吗?
是的。可以查看 link:springintegration.adoc[Spring 集成] 章节的文档。

[[what-type-custom-mapping]]
=== 什么类型的数据映射需要自定义xml的映射文件?
只有不能基于域名的隐式映射的域需要一个自定义XML 映射定义。
理想情况下，大多数你的域映射可以自动进行，只有很少例外案例需要在xml映射文件中显式的域映射。

[[matching-prop-names]]
=== 如果我的源和目标对象包含所有匹配的属性名称，我还需要任何xml映射定义吗?
不需要了。只要调用映射器就可以。你不需要任何显式的xml映射项在这个源和目标对象组合上。

[[is-bidirectional]]
=== 针对需要xml映射文件定义的映射是否是双向的，或者还需要我定义第二个xml文件进行另外一个方向的映射?
所有的映射定义都是双向的，因此你只需要一个映射定义。你可以映射 a --> b 和 b--> a 使用单独一个映射定义。

[[how-xml-loaded]]
=== 自定义xml映射文件是如何加载的?
Dozer 将会搜索整个 classpath 路径来查找所定义的文件。

[[how-to-load-file]]
=== 我如何加载一个不在classpath中的映射文件?
是的，你可以在classpath外部载入文件，通过加入 "file:" 前缀到资源名称。 例如) "file:c:\somedozermapping.xml"

[[dozer-debug]]
=== 我如何知道Dozer是否已经正确的初始化和加载我的xml映射文件的?
设定 -Ddozer.debug 系统属性。如果这个属性被设定了，Dozer的初始化信息将被发送到 System.out。如果你熟悉 log4j, 这个操作类似与设定 -Dlog4j.debug 系统属性。

[[dozer-perf]]
=== Dozer是如何工作的?
我们坚信Dozer运行得很好，性能是我们的高优先级要求。我们花费了大量的时间来调优代码和优化瓶颈。

性能开销取决域使用场景的复杂性和所需要映射的域数目。在我们平均的映射场景中的性能测试，类映射花费的时间从1/8毫秒到2毫秒之间。
粗略的估计每毫秒能够映射大约 50 - 450 个域。然而在任何正式基准下的参数都不可能转化为你自己应用中的可信赖的结果。你的应用程序是不同的，你包含有自己独特的用例。

Dozer已经成功应用于大型的和非常高事务量的企业系统中，没有带来任何性能问题。
但是我们任何建议在你的应用中运行性能测试，来确定你系统中真实性能开销。你可以自己决定这些开销是否在整个系统上下文中是否可接受。

[[jdk-support]]
=== 那个版本的JDK被支持?
JDK 1.8 或者更高。

[[maven-repo]]
=== IDozer在maven仓库吗?
是的，我们将继续尽最大的努力来发布Dozer未来的版本到仓库中。

[source,xml,prettyprint]
----
<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-core</artifactId>
    <version>{dozer-version}</version>
</dependency>
----

[[good-environment]]
=== Dozer对环境友好吗?
是的，dozer不燃烧化石燃料，以及符合 EPA的推荐排放标准。

[[custom-converters]]
=== 我如何实现在两个数据类型中进行自定义的映射逻辑，Dozer在进行映射的时候如何调用自定义的逻辑?
是的，一个非常有用的Dozer特性，提供了一个自定义转化器的概念。自定义转化器用于进行自定义的两个对象之间的映射。
在配置块中，你可以添加一些自己的xml来告诉Dozer来进行自定义的确定A类和B类的转化器。
当类A和类B的组合中定义了自定义转化器，Dozer将会调用自定义转化器进行数据映射而不是标准的映射逻辑。

[source,xml,prettyprint]
----
<custom-converters>
    <converter type="com.github.dozermapper.core.converters.SomeCustomConverter">
        <class-a>com.github.dozermapper.core.vo.SomeCustomDoubleObject</class-a>
        <class-b>java.lang.Double</class-b>
    </converter>
</custom-converters>
----

[[deep-mapping]]
=== 我是否可以映射一个域到另外一个在目标对象n层深的域?
是的。Dozer支持使用点注释来标记嵌套域。正如其他的dozer域映射一样，他们都是双向的。

[source,xml,prettyprint]
----
<field>
    <a>someNestedObj.someOtherNestedObj.someField</a>
    <b>someOtherField</b>
</field>
----

[[mult-fields-to-single-field]]
=== 我如何映射多个域到一个独立的域?
Dozer目前不支持这个。由于其中实现它的复杂性，这个特性当前也不在既定目标图中。一个可能的解决方案是包装多个域到一个自定义的复杂类型中，然后定义一个自定义映射器来映射复杂类型和独立的域。通过这种方式，你可以在映射器中处理自定义的逻辑来映射三个域到一个简单的域。

[[infinite-loop]]
=== 如果我映射的数据对象包含双向的关系，其是否会导致一个死循环和堆栈溢出的错误?
不，Dozer会使用避免死循环的逻辑来处理双向的数据对象关系。

[[index-mapping]]
=== 我如何映射一个集合中的对象到一个域?
你可以使用带下标的映射。

[source,xml,prettyprint]
----
<field>
    <a>usernames[0]</a>
    <b>username1</b>
</field>
----

[[complex-to-map]]
=== 我如何映射复杂的队形到哈希列表和反向处理?
你可以直接映射整个复杂的对象到 java.util.Map，或反向。
当你这样做的时候你需要显式的定义一个唯一的 map-id来标识整个映射。这将被用作确定运行时哪个映射被使用。
每一个复杂类型上的属性都将被映射到 java.util.Map。你不需要显式的定义这些映射。如果属性名称不是map的键，只需要设定一个自定义域映射的键属性。

[source,xml,prettyprint]
----
<mapping map-id="myTestMapping">
    <class-a>com.github.dozermapper.core.vo.map.SomeComplexType</class-a>
    <class-b>java.util.Map</class-b>
    <field>
        <a>stringProperty2</a>
        <b key="myStringProperty">this</b>
    </field>
</mapping>
----

[[is-accessible]]
=== 我如何映射不包含对应getter/setter方法的域?
你可以告诉Dozer直接使用域(包括私有方法)，通过指定 is-accessible="true"。

[source,xml,prettyprint]
----
<field>
    <a>fieldA</a>
    <b is-accessible="true">fieldB</b>
</field>
----

[[private-constructors]]
=== 我的一些数据对象不包含公开的构造函数，Dozer是否支持这种案例?
是的。当你创建的一个目标新对象没有包含公开的无参数构造函数，dozer将会自动检测到一个私有的构造函数来使用。
当一个数据对象没有包含私有的构造函数，你可以定义一个自定义的beanfactory来创建一个目标对象的新实例。

[[enum-support]]
=== Dozer 支持 JDK 1.5的枚举类型吗?
是的。枚举到枚举的映射是自动处理的。

[[xmlbeans-jaxb]]
=== Dozer 支持 XMLBeans和JAXB生成的数据对象吗?
Dozer支持映射POJOs到 XMLBeans 对象。使用XMLBeanFactory来处理你所想创建的任何XMLBeans。
这个工厂也可以被使用作映射任何在深度映射需要实例化的域，其中不是常规的POJOS,而是XMLBeans。

Dozer也支持映射POJOS到JAXB对象。使用JAXBBeanFactory来处理任何你想创建的JAXB对象。

[[eclipse-plugin]]
=== 是否包含支持Dozer的 Eclipse 插件或可视化编辑器?
不，但是我们认为其是一个很好的附加品。它将有助于图形化的映射两个对象，可以有自定义xml定义的自动生成，伴随这能够可视化的查看一个映射定义。如果任何人在创建eclipse 插件可视化上有经验，并且有兴趣来做这个特性，请让我们知道!

[[collection-hints]]
=== 当映射集合的时候，我如何告诉Dozer我需要映射的目标集合的数据类型?
暗示被支持来处理这种用例。如果你使用的是JDK1.5的泛型，暗示是不需要的。因为类型能够被Dozer自动检测到。
如果你没有使用泛型，转化包含不同类型对象的一个集合/数组到另外一个集合/数组，你
可以定义一个暗示来让Dozer知道你想在目标集合中所需要创建的对象类型。如果暗示没有被定义在目标域上，目标集合将会使用和源集合中一样的数据类型进行填充。

[source,xml,prettyprint]
----
<field>
    <a>someList</a>
    <b>otherList</b>
    <b-hint>com.github.dozermapper.core.vo.TheFirstSubClassPrime</b-hint>
</field>
----

[[bypass-null]]
=== 我如何告诉Dozer忽略映射 null 或空的字符串值?
你可以忽略映射null值，通过定义 map-null="false"。如果这个被定义，假如源值是null，目标值的setter方法在运行时会被忽略，
目标值的setter方法将不会被调用。这个可以被定义在映射或者是类级别上。

你可以忽略映射任何空字符串通过指定 map-empty-string="false"。如果这个被定义，假如目标值是空字符串，
目标域映射将在运行时被忽略，目标值的setter方法将不会被调用。这个可以定义在映射或类型级别上。

[[encapsulation]]
=== 我是否需要封装对象间复制数据的逻辑?
这是你应该使用的选项。尽管你是否使用Dozer进行对象中数据映射，我们相信这是一个好的设计模式来促进重用，封装底层的实现，使得代码单元可独立的测试。
这个装配器接口封装了将一个源对象映射为目标对象的逻辑。使用装配器类型的类可以给你最大的灵活性来修改底层的映射，而不需要影响客户端或者是协议。
另外一个使用装配器的好处是它使得针对映射的单元测试更加容易和专注。
如果你需要决定是否一个特定的BUG是由于映射对象，只需要编写一个装配器单元测试来重发使用案例。
如果你封装了你的数据映射逻辑，你可以使用Dozer来处理大多数的映射，如果你包含一个实际的边角例子，
你可以灵活的处理代码映射针对任何对象和域。例如，你可以可以通过Dozer来处理映射解决99%的你的域，
然后包含一些手动的映射来处理一些特殊的域。这些功能都在装配器中不需要客户掌握任何底层实现。

如果装配器类型的类是默认和仅仅只复制源对象中的数据到目标对象，这是最佳工作情况。
任何复杂的针对目标对象后续业务逻辑处理可以在一个更高级别有效的类上进行处理。

如下是一个简单的使用Dozer作为底层实现装配器类型案例。

[source,java,prettyprint]
----
public class SomeAssemblerImpl implements SomeAssembler { 
  
  private Mapper dozerMapper;
 
  public DestObject assembleDestObject(SrcObject src) { 
    return dozerMapper.map(src, DestObject.class); 
  } 
 
}
----

[[dozer-unit-tests]]
=== 我是否需要为使用Dozer进行处理的映射逻辑编写单元测试?
当然，首先我们强烈建议编写单元测试。即使你不使用Dozer来进行两个对象之间的数据映射，这断逻辑也是需要独立的测试。
数据映射逻辑(特别是手写的)是容易错误，包含一个单元测试是无价的。
有代表性的是在一个系统的多个区域进行两个对象的映射是必须的。
因此针对中心化映射逻辑的单元测试使你能够独立的测试数据映射逻辑。
封装数据映射逻辑和包含对逻辑的单元测试的最大好处是能够让你切换底层的实现。

针对存量的系统需要迁移到Dozer上的，我们建议首先封装已经存在硬编码数据映射到一个类的装配器类型中，然后对其编写单元测试。然后切换这个硬编码映射逻辑到Dozer中，单元测试将会确保你的安全。迁移到Dozer上可以是增量式的，这或许是最好的针对存量系统的策略。

无论你是否使用Dozer,针对数据映射的单元测试是无趣的和让人讨厌的，但是有一个技巧或许有帮助。
如果你有一个装配器来支持两个对象的双向映射，在你的单元测试中你可以进行如下相似的例子。
这个假定你已经处理好你的数据对象的equals()方法。
这个思路是你可以映射一个源对象到目标对象，然后返回，原始的源对象应该和最后一次映射返回的对象相同，如果域正确的被映射。在测试案例中，你需要填充所有可能的域到原始对象上来确保所有的域在映射逻辑是工作的。

[source,javaprettyprint]
----
public void testAssembleSomeObject() throws Exception {      
  SrcObject src = new SrcObject();
  src.setSomeField("somevalue");
  src.setSomeOtherField("make sure you set all the src fields "
    + "with values so that you fully test the data mappings");
    
  DestObject dest = assembler.assembleDestObject(src);
  SrcObject mappedSrc = assermbler.assembleSrcObject(dest);
  
  assertEquals("fields not mapped correctly", src, mappedSrc);
}
----

验证你的装配器恰当的来处理null值是一个好的实践。在如下的测试案例中没有一个源域被填充。
如果装配器不能合理的处理null值，当装配器被调用的时候将会抛出异常。

[source,java,prettyprint]
----
public void testAssembleSomeObject_NullValues() throws Exception {      
  SrcObject src = new SrcObject();
    
  DestObject dest = assembler.assembleDestObject(src);
  SrcObject mappedSrc = assermbler.assembleSrcObject(dest);
  
  assertEquals("fields not mapped correctly", src, mappedSrc);
}
----

[[config-as-singleton]]
=== Dozer映射器是否需要配置成单例?
是的。`Mapper` 实例将被尽可能使用。针对每一个 `Mapper`实例， 每一个映射文件被载入和解析。
你需要为你的配置一次配置完 `Mapper`，并在你的应用中重用。`Mapper`的实现是线程安全的。

[[component-mappings]]
=== 包含一个大的xml映射文件或包含多个小的映射文件，哪种方式好?
我们建议组件化你们的映射文件而不是包含一个大的映射文件。

[[debugging-dozer]]
=== 调试Dozer的最好方式是什么?
你可以设定 -Ddozer.debug 系统属性来查看一次性的初始化信息。你可以看到如下相似的信息....

[source,prettyprint]
----
dozer: Trying to find Dozer configuration file: dozer.properties
dozer: Using URL [file:/local/subversion_projects/dozer/trunk/target/test-classes/dozer.properties] for Dozerglobal property configuration
dozer: Reading Dozer properties from URL[file:/local/subversion_projects/dozer/trunk/target/test-classes/dozer.properties]
dozer: Finished configuring Dozer global properties
dozer: Initializing Dozer. Version: ${project.version}, Thread Name:main
dozer: Initializing a new instance of the dozer bean mapper.
dozer: Using the following xml files to load custom mappings for the bean mapper instance:[fieldAttributeMapping.xml]
dozer: Trying to find xml mapping file: fieldAttributeMapping.xml
dozer: Using URL [file:/local/subversion_projects/dozer/trunk/target/test-classes/fieldAttributeMapping.xml]to load custom xml mappings
dozer: Successfully loaded custom xml mappings from URL:[file:/local/subversion_projects/dozer/trunk/target/test-classes/fieldAttributeMapping.xml]
----

为了调试独立的域映射在类之间，只需要设定日志级别为 "org.dozer.MappingProcessor=DEBUG"。例如，如果你已经使用
log4j，你只需要添加如下的项到你的 log4j 配置文件中 "log4j.category.org.dozer.MappingProcessor=DEBUG"。 这将显示每一个Dozer实际进行的从源到目标值域映射。
你将看到如下相似的输出....

[source,prettyprint]
----
MAPPED: SimpleObj.field1 --> SimpleObjPrime.field1 VALUES: 
one --> one MAPID: someMapId
MAPPED: SimpleObj.field2 --> SimpleObjPrime.field2 VALUES: 
2 --> 2 MAPID: someMapId
MAPPED: SimpleObj.field3 --> SimpleObjPrime.field3 VALUES: 
3 --> 3 MAPID: someMapId
MAPPED: SimpleObj.field4 --> SimpleObjPrime.field4 VALUES: 
44.44 --> 44.44 MAPID: someMapId
MAPPED: SimpleObj.field6 --> SimpleObjPrime.field6 VALUES: 
66 --> 66 MAPID: someMapId
----

[[global-config]]
=== 设定全局配置的最好方式是什么?
我们建议使用一个独立的映射xml文件来处理全局配置。你可以命名为例如 dozer-global-configuration.xml。全局配置文件的样例如 ......

[source,xml,prettyprint]
----
<?xml version="1.0" encoding="UTF-8"?>
<mappings xmlns="http://dozermapper.github.io/schema/bean-mapping"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://dozermapper.github.io/schema/bean-mapping http://dozermapper.github.io/schema/bean-mapping.xsd">
    <configuration>
        <stop-on-errors>true</stop-on-errors>
        <date-format>MM/dd/yyyy HH:mm</date-format>
        <wildcard>false</wildcard>
        <custom-converters>
            <converter type="com.github.dozermapper.core.converters.TestCustomConverter">
                <class-a>com.github.dozermapper.core.vo.CustomDoubleObject</class-a>
                <class-b>java.lang.Double</class-b>
            </converter>
        </custom-converters>
    </configuration>
</mappings>
----

[[submitting-support-request]]
=== 提交bug，功能请求或补丁的最佳方式是什么?
我们珍惜你的建议和赞赏每个人花时间来提交支持请求。
请通过如下的连接提交所有的请 link:https://github.com/DozerMapper/dozer[Dozer的GitHub项目页面]
