:dozer-version: 6.5.0-SNAPSHOT

== 入门
=== 下载发布包
如果你在使用 link:https://maven.apache.org/[Apache Maven], 只需要简单的复制这些依赖到你的项目中。

[source,xml,prettyprint,subs="verbatim,attributes"]
----
<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-core</artifactId>
    <version>{dozer-version}</version>
</dependency>
----

=== 第一个映射
作为你的第一个映射，假定两个数据对象包含相同的属性名称。

[source,java,prettyprint]
----
Mapper mapper = DozerBeanMapperBuilder.buildDefault();
DestinationObject destObject = mapper.map(sourceObject, DestinationObject.class);
----

在Dozer映射执行之后，结果是新的目标对象中所有和源对象中名称相同的域包含值。
如果任何映射属性包含不同数据类型的话，Dozer映射引擎将自动进行类型转化。
此时你已经完成你的第一个 Dozer 映射。接下来的部分将会介绍如何通过自定义 xml 文件进行自定义映射。

*重要:* 针对真实的应用，不建议每次映射对象的时候新建一个 Mapper实例，而是重用这个已经新建的实例。

=== 通过XML 定义自定义映射
如果需要映射的两个不同类型的数据对象不包含相同的属性名称，你就需要添加一个类型映射条目到自定义的映射xml文件中。
这些映射xml文件都能在运行时被 Dozer映射引擎使用。

在从源域对象到目标域进行复制的时候，Dozer 自动进行任何的类型转化。
Dozer映射是双向的，因此如果你想映射目标对象到源对象，你不需要添加额外的类映射到xml文件中。

*重要:* 相同名字的域不需要在映射xml文件中定义。Dozer将映射所有相同属性名称的域从源对象到目标对象上。ination object.

例如:

[source,xml,prettyprint]
----
<mapping>
    <class-a>yourpackage.yourSourceClassName</class-a>
    <class-b>yourpackage.yourDestinationClassName</class-b>
    <field>
        <a>yourSourceFieldName</a>
        <b>yourDestinationFieldName</b>
    </field>
</mapping>
----

完成的Dozer映射文件将像下面的一样。
link:./mappings.adoc[自定义映射] 章节包含了更多关于映射选项信息，从而帮助你了解更多复杂的用例。

[source,xml,prettyprint]
----
<?xml version="1.0" encoding="UTF-8"?>
<mappings xmlns="http://dozermapper.github.io/schema/bean-mapping"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://dozermapper.github.io/schema/bean-mapping http://dozermapper.github.io/schema/bean-mapping.xsd">
    <configuration>
        <stop-on-errors>true</stop-on-errors>
        <date-format>MM/dd/yyyy HH:mm</date-format>
        <wildcard>true</wildcard>
    </configuration>
    <mapping>
        <class-a>yourpackage.yourSourceClassName</class-a>
        <class-b>yourpackage.yourDestinationClassName</class-b>
        <field>
            <A>yourSourceFieldName</A>
            <B>yourDestinationFieldName</B>
        </field>
    </mapping>
</mappings>
----

=== Dozer和依赖注入框架
Dozer 不独立域已经存在的依赖注入框架。(link:https://en.wikipedia.org/wiki/Dependency_injection[DI]).
然而通常的目标是为了支持更加传统的开箱即用的封装使用案例。可以查看 link:springintegration.adoc[Spring 集成] 手册来可选的初始化 Dozer 在 Sping 依赖注入框架的上下文中。
