== 映射map中的备用属性
=== Map 转化为 Map
Dozer 将会映射 java.util.Map 到另外一个 java.util.Map。如果包含复杂的类型可以通过使用提示来帮助实现深度的递归映射。如果目标map存在，它将把元素添加到存在的map中。

[source,xml,prettyprint]
----
<mapping>
    <class-a>com.github.dozermapper.core.vo.map.MapToMap</class-a>
    <class-b>com.github.dozermapper.core.vo.map.MapToMapPrime</class-b>
    <field>
        <a>standardMapWithHint</a>
        <b>standardMapWithHint</b>
        <a-hint>com.github.dozermapper.core.vo.TestObject</a-hint>
        <b-hint>com.github.dozermapper.core.vo.TestObjectPrime</b-hint>
    </field>
</mapping>
----

=== 映射域级别的属性到 java.util.Map 或一个自定义的 Map 中使用独立的Get/Set 方法
Dozer 支持映射map的备用属性在域级别。这种映射不仅仅可以通过实现 java.util.Map 接口也可以通过自定义包含独立的Get/Set 方法的map。

在这个例子中域A是一个简单字符串，它将被映射到HashMap类型的域B中。在HashMap中的key将会是 "stringProperty" (属性名称)，而值为存储在域A中的值。

[source,xml,prettyprint]
----
<mapping>
    <class-a>com.github.dozermapper.core.vo.map.PropertyToMap</class-a>
    <class-b>com.github.dozermapper.core.vo.map.MapToProperty</class-b>
    <field>
        <a>stringProperty</a>
        <b>hashMap</b>
    </field>
</mapping>
----

在这个例子中域A是一个简单字符串，它将被映射到HashMap类型的域B中。在HashMap中的key将会是 "myStringProperty"，而值为存储在域A中的值。此外注意域A包含一个独立的setter()方法。

[source,xml,prettyprint]
----
<mapping>
    <class-a>com.github.dozermapper.core.vo.map.PropertyToMap</class-a>
    <class-b>com.github.dozermapper.core.vo.map.MapToProperty</class-b>
    <field>
        <a set-method="addStringProperty2">stringProperty2</a>
        <b key="myStringProperty">hashMap</b>
    </field>
</mapping>
----

在这个例子中域A是一个简单字符串，它将被映射到自定义的map类型的域B中。在HashMap中的key将会是 "myCustomProperty"，而值为存储在域A中的值。此外注意域B中包含独立的map getter() 和 map setter()方法名称。如果你在使用自定义的map，你必须显式的设定map的Get/Set方法名称。如果你的自定义map实现一个接口或者是抽象类，也可以通过使用目标提示的方法。

[source,xml,prettyprint]
----
<mapping>
    <class-a>com.github.dozermapper.core.vo.map.PropertyToMap</class-a>
    <class-b>com.github.dozermapper.core.vo.map.MapToProperty</class-b>
    <field>
        <a>stringProperty3</a>
        <b map-get-method="getValue" map-set-method="putValue" key="myCustomProperty">customMap</b>
    </field>
    <field>
        <a>stringProperty4</a>
        <b map-get-method="getValue" map-set-method="putValue" key="myCustomNullProperty">nullCustomMap</b>
        <b-hint>com.github.dozermapper.core.vo.map.CustomMap</b-hint>
    </field>
    <field>
        <a>stringProperty5</a>
        <b map-get-method="getValue" map-set-method="putValue">customMap</b>
    </field>
</mapping>
----

=== 使用独立的Get/Set方法进行映射类级别的属性到 java.util.Map 或一个自定义的 Map 
Dozer也能够直接映射完整的复杂的对象到 java.util.Map 或一个自定义的map对象上。该例子将展示声明一个在复杂对象(PropertyToMap)和 java.util.Map上的映射。当这样做的时候，你需要显式的使用一个独立的 map-id来标注这个映射。这个标记将能够在运行时确定哪一个映射被使用。每一个在 PropertyToMap类中的属性将被映射到 the java.util.Map。你不需要显式的定义蛇蝎映射。 排除域映射将能用来在运行时排除一些域。如果属性名称和map中的key不一致，只会设定自定义域中的key映射。stringProperty2 中的映射将显示这个例子。

第二个例子将会显式如何设定一个自定义的map对象。唯一的区别是这里你需要显式的设定 map-set-method 和
map-get-method 的值。这些对应 java.util.Map get() 和 put() 方法。

[source,xml,prettyprint]
----
<mapping map-id="myTestMapping">
    <class-a>com.github.dozermapper.core.vo.map.PropertyToMap</class-a>
    <class-b>java.util.Map</class-b>
    <field>
        <a set-method="addStringProperty2">stringProperty2</a>
        <b key="myStringProperty">this</b>
    </field>
    <field-exclude>
        <a>excludeMe</a>
        <b>this</b>
    </field-exclude>
</mapping>
<mapping map-id="myCustomTestMapping">
    <class-a>com.github.dozermapper.core.vo.map.PropertyToMap</class-a>
    <class-b map-set-method="putValue" map-get-method="getValue">
      com.github.dozermapper.core.vo.map.CustomMap
  </class-b>
    <field>
        <a set-method="addStringProperty2">stringProperty2</a>
        <b key="myStringProperty">this</b>
    </field>
    <field-exclude>
        <a>excludeMe</a>
        <b>this</b>
    </field-exclude>
</mapping>
----

下面的例子将会显示如何使用这些映射。注意这些域映射通过 map-id 进行引用。第一个域映射将会使用
myTestMapping 定义映射。通用的用法也适用于自定义映射。

[source,prettyprint]
----
<mapping>
    <class-a>com.github.dozermapper.core.vo.map.MapTestObject</class-a>
    <class-b>com.github.dozermapper.core.vo.map.MapTestObjectPrime</class-b>
    <field map-id="myTestMapping">
        <a>propertyToMap</a>
        <b>propertyToMapMap</b>
    </field>
    <field map-id="myTestMapping">
        <a>propertyToMapToNullMap</a>
        <b>nullPropertyToMapMap</b>
        <b-hint>java.util.HashMap</b-hint>
    </field>
    <field map-id="myCustomTestMapping">
        <a>propertyToCustomMap</a>
        <b>propertyToCustomMapMap</b>
    </field>
</mapping>
----

类级别的map映射也可以当做一个标准的映射。针对这些 dozer包含一个新的API。在传统的源类型和目标类型此外还可以传递映射的引用ID。

[source,java,prettyprint]
----
// Example 1
PropertyToMap ptm = new PropertyToMap();
ptm.setStringProperty("stringPropertyValue");
ptm.addStringProperty2("stringProperty2Value");
Map map = Mapper.map(ptm, HashMap.class, "myTestMapping");

// Example 2
CustomMap customMap = mapper.map(ptm, CustomMap.class, "myCustomTestMapping");

// Example 3
CustomMap custom = new CustomMap();
custom.putValue("myKey", "myValue");
Mapper.map(ptm, custom, "myCustomTestMapping");

// Example 4 - Map Back
Map map = new HashMap();
map.put("stringProperty", "stringPropertyValue");
PropertyToMap property = mapper.map(map, PropertyToMap.class, "myTestMapping");
assertEquals("stringPropertyValue", property.getStringProperty());
----
