== Spring 框架集成
添加 DozerBeanMapperFactoryBean 到你的spring配置文件中。
映射文件属性上你需要定义任何需要自定义创建的映射文件。如果你没有任何自定义映射，这个列表可以为空。
也可以设定自定义的事件监听器和bean工厂。

我们提供了 `dozer-spring4` 来集成spring 应用。
如果你在使用 :https://maven.apache.org/[Apache Maven], 简单的复制下面的依赖到你的项目中。

.pom.xml
[source,xml,prettyprint,subs="verbatim,attributes"]
----
<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-core</artifactId>
    <version>{dozer-version}</version>
</dependency>
<dependency>
    <groupId>com.github.dozermapper</groupId>
    <artifactId>dozer-spring4</artifactId>
    <version>{dozer-version}</version>
</dependency>
----

=== 配置

添加 `DozerBeanMapperFactoryBean` 到你的Spring配置文件中。
其中 `mappingFiles` 属性中你需要配置你所创建的需要自定义的映射文件。
如果你没有自定义映射，这个列表可以为空。也可以设定自定的时间监听器和类工厂。

[重要]
====
你需要定义Dozer映射器实例为  *singleton="true"*。 你需要通过这种方法类配置映射器实例，
因此你不需要在你的整个应用周期内针对每一个映射重复的加载和初始化映射文件。
每次映射中都重新初始化映射文件将是无效和没有必要的。DozerBeanMapper 类是线程安全的。
====

==== 基于XML的配置

注意工厂Bean支持Spring Resources,这意味着你可以通过classpath的标记来载入xml文件，例如：

[source,xml,prettyprint]
----
<bean id="dozerMapper" class="com.github.dozermapper.spring.DozerBeanMapperFactoryBean">
    <property name="mappingFiles" value="classpath*:/*mapping.xml" />
    <property name="customConverters">
        <list>
            <bean class="com.github.dozermapper.core.converters.CustomConverter" />
        </list>
    </property>
    <property name="eventListeners">
        <list>
            <bean class="com.github.dozermapper.core.listeners.EventListener" />
        </list>
    </property>
    <property name="factories">
        <map>
            <entry key="id" value-ref="bean-factory-ref" />
        </map>
    </property>
</bean>
----

此外，你还可以定义 `DozerBeanMapper`，使用 `dozer` 命名空间如下所示:

[source,xml,prettyprint]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dozer="http://dozermapper.github.io/schema/dozer-spring"
       xsi:schemaLocation="
         http://www.springframework.org/schema/beans
         http://www.springframework.org/schema/beans/spring-beans.xsd
         http://dozermapper.github.io/schema/dozer-spring
         https://dozermapper.github.io/schema/dozer-spring.xsd
       ">

    <dozer:mapper id="dozerMapper"/>

</beans>
----

==== 基于java代码的配置

当使用Java配置的时候，bean的定义如下:

[source,java,prettyprint]
----
@Configuration
public class DozerConfig {
    @Bean
    public DozerBeanMapperFactoryBean dozerMapper(
        ResourcePatternResolver resourcePatternResolver) throws IOException {
        DozerBeanMapperFactoryBean factoryBean = new DozerBeanMapperFactoryBean();
        factoryBean.setMappingFiles(
            resourcePatternResolver.getResources("classpath*:/*mapping.xml"));
        // ...
        return factoryBean;
    }
}
----

=== 如何在你的应用中使用

使用Spring来获取 Dozer Mapper......

===== 查找的基本用法

你可以从Spring的`ApplicationContext`(`BeanFactory`)中查找Dozer Mapper。

[source,java,prettyprint]
----
Mapper dozerMapper = applicationContext.getBean("dozerMapper", Mapper.class);
DestinationObject destObject = dozerMapper.map(sourceObject, DestinationObject.class);
----

===== 基于注入的用法

此外你还可以使用Spring 的DI容器将Dozer Mapper注入到你的组件中。

[source,java,prettyprint]
----
@Component
public class YourComponent {
    private final Mapper dozerMapper;
    public YourComponent(Mapper dozerMapper) {
        this.dozerMapper = dozerMapper;
    }
    public void anyMethod() {
        // ...
        DestinationObject destObject =
            dozerMapper.map(sourceObject, DestinationObject.class);
        // ...
    }
}
----

=== 如何在Spring Boot应用中使用

请查看:springBootIntegration.adoc[Spring Boot Integration] 章节。
