== 使用
=== Dozer Bean 映射器
在我们准备着手自定义xml bean映射之前，让我们看看一个简单的使用Dozer的例子。
Dozer 映射的实现包含有一个称作 map的方法，其包含源对象和一个目标对象或者目标对象数据类型参数。
在映射两个对象之后，它将返回包含所有它映射属性的目标对象。

[source,java,prettyprint]
----
Mapper mapper = DozerBeanMapperBuilder.buildDefault();
DestinationObject destObject = mapper.map(sourceObject, DestinationObject.class);
----

或...

[source,java,prettyprint]
----
DestinationObject destObject = new DestinationObject();
mapper.map(sourceObject, destObject);
----

Dozer 有两种运行模式 : 隐式和显式。

隐式模式是默认激活的，最大化的解决你的映射问题。
它使用一个简单的假设如果两个对象需要映射，其相同名字的属性需要被映射。如果你需要额外的映射，其不能通过名称进行导出，你可以如下的方法添加
link:mappings.adoc[XML], link:annotations.adoc[注释] 或 link:apimappings.adoc[API].

显式模式假定直到你明确定义前没有映射需要被执行或者猜测。显式模式的代码量高，但是有事你可能需要完全控制映射过程的处理，这个方式也被使用到需要生产上的应用。隐式和显式的映射切换通过使用Dozer中的wildcard 标记。

=== 注入自定义映射文件
Dozer映射 xml文件定义任何Dozer映射引擎不能自动处理的自定义映射。
任何自定义的映射文件都需要被注入到 `Mapper` 实现，通过 `DozerBeanMapperBuilder#withMappingFiles(..)` 方法。

首选上你会使用一个IOC框架，例如spring来进行Dozer的依赖注入。此外，映射文件的注入也可以通过编码方式来实现。
下面是一个编码方式来创建一个bean映射器。注意这不是推荐的方式来获取bean映射器。
每一个新实例都需要被初始化，这将消耗时间和资源。如果你想这样使用映射器可以使用单例模式。

[source,java,prettyprint]
----
Mapper mapper = DozerBeanMapperBuilder.create()
        .withMappingFiles("dozerBeanMapping.xml", "someOtherDozerBeanMappings.xml")
        .build();

DestinationObject destObject = mapper.map(sourceObject, DestinationObject.class);
----

=== Spring 集成
西面是一个例子展示如何通过spring进行映射器bean的配置。

[source,xml,prettyprint]
----
<bean id="mapper" class="com.github.dozermapper.core.DozerBeanMapper">
    <property name="mappingFiles">
        <list>
            <value>dozer-global-configuration.xml</value>
            <value>dozer-bean-mappings.xml</value>
            <value>more-dozer-bean-mappings.xml</value>
        </list>
    </property>
</bean>
----
