== 通过XML进行配置
主要的Dozer行为可以通过XML映射文件进行配置。在五个不同范围中的配置会影响他们所在的元素：
全局、每个类映射、在独立的每个类层级，每个领域映射，和在独立的域级别。

=== 配置范围

==== 全局配置
配置块用于谁当全局的缺省配置。同样的，任何自定义转化器也将在这个部分中定义。配置块完全是可选的。

Dozer 支持包含多个映射文件的能力，但是只有一个全局配置在多个映射文件中。
我们建议使用一个独立的映射xml文件来定义单独的全局配置。*隐式的映射将会继承配置的缺省值*。

下面是一个配置块的样例。

[source,xml,prettyprint]
----
<configuration>
    <date-format>MM/dd/yyyy HH:mm</date-format>
    <stop-on-errors>true</stop-on-errors>
    <wildcard>true</wildcard>
    <custom-converters>
        <!-- these are always bi-directional -->
        <converter type="com.github.dozermapper.core.converters.TestCustomConverter">
            <class-a>com.github.dozermapper.core.vo.TestCustomConverterObject</class-a>
            <class-b>another.type.to.Associate</class-b>
        </converter>
    </custom-converters>
</configuration>
----

所有的全局配置以独自的xml标签形式包含自己的值。

==== 每个类映射
全局配置(或者它们的缺省值)可以被独立的映射级别所覆盖。这里配置值通过使用 name="value" 属性。
它们将影响所有在两个类之间的映射操作。

[source,xml,prettyprint]
----
<mapping wildcard="false" date-format="MM/dd/yyyy HH:mm">
    <class-a>com.github.dozermapper.core.vo.SpringBean</class-a>
    <class-b>com.github.dozermapper.core.vo.SpringBeanPrime</class-b>
    <field>
        <a>anAttributeToMap</a>
        <b>anAttributeToMapPrime</b>
    </field>
</mapping>
----

==== 在独立的类级别
有事，你可能想要设置这两个类中的一个。这可以通过将属性放到 `class-a` 或者 `class-b`标签中:

[source,xml,prettyprint]
----
<mapping>
    <class-a is-accessible="true">com.github.dozermapper.core.vo.SpringBean</class-a>
    <class-b>com.github.dozermapper.core.vo.SpringBeanPrime</class-b>
    <field>
        <a>anAttributeToMap</a>
        <b>anAttributeToMapPrime</b>
    </field>
</mapping>
----

==== 每个域映射
同样的，你可以修改指定域队的映射行为:

[source,xml,prettyprint]
----
<mapping>
    <class-a>com.github.dozermapper.core.vo.SpringBean</class-a>
    <class-b>com.github.dozermapper.core.vo.SpringBeanPrime</class-b>
    <field remove-orphans="false">
        <a>anAttributeToMap</a>
        <b>anAttributeToMapPrime</b>
    </field>
</mapping>
----

==== 在每个独立的域级别
最后，有些配置可以使用到一个域中:

[source,xml,prettyprint]
----
<mapping>
    <class-a>com.github.dozermapper.core.vo.SpringBean</class-a>
    <class-b>com.github.dozermapper.core.vo.SpringBeanPrime</class-b>
    <field>
        <a get-method="getTheAttribute">anAttributeToMap</a>
        <b>anAttributeToMapPrime</b>
    </field>
</mapping>
----

=== 可用的配置设定
[[label-config-options]]下表中罗列了可用的配置选项和映射方向，以及他们所适用范围，手册的章节中包含更多信息:

|===
|名称                      |全局 |类映射 |独立类|域映射 |单个域 |手册章节

|allowed-exceptions        |X      |              |            |              |             |see below
|custom-converter          |       |              |            |X             |             |link:customconverter.adoc[Custom Converters]
|custom-converter-id       |       |              |            |X             |             |link:customconverter.adoc[Custom Converters]
|custom-converter-param    |       |              |            |X             |             |link:customconverter.adoc[Custom Converters]
|copy-by-reference         |       |              |            |X             |             |link:copybyreference.adoc[Copy By Reference]
|copy-by-references        |X      |              |            |              |             |link:copybyreference.adoc[Copy By Reference]
|create-method             |       |              |X           |              |X            |link:customCreateMethod.adoc[Custom Create Method]
|bean-factory              |X      |X             |X           |              |             |link:custombeanfactories.adoc[Custom Bean Factories]
|date-format               |X      |X             |            |              |X            |link:stringtodatemapping.adoc[String to Date Mapping]
|factory-bean-id           |       |              |X           |              |             |link:custombeanfactories.adoc[Custom Bean Factories]
|get-method                |       |              |            |              |X            |link:custommethods.adoc[Custom Methods]
|is-accessible             |       |              |X           |              |X            |link:immutable.adoc[Mapping immutable types]
|key                       |       |              |            |              |X            |link:mapbackedproperty.adoc[Map Mapping]
|map-empty-string          |X      |X             |X           |              |             |link:exclude.adoc[Excluding Fields]
|map-id                    |       |X             |            |              |             |link:contextmapping.adoc[Context Based Mapping]
|map-null                  |X      |X             |X           |              |             |link:exclude.adoc[Excluding Fields]
|map-set-method            |       |              |X           |              |X            |link:mapbackedproperty.adoc[Map Mapping]
|map-get-method            |       |              |X           |              |X            |link:mapbackedproperty.adoc[Map Mapping]
|relationship-type         |X      |X             |            |X             |             |link:collectionandarraymapping.adoc[Collection Mapping]
|remove-orphans            |       |              |            |X             |             |link:collectionandarraymapping.adoc[Collection Mapping]
|set-method                |       |              |            |              |X            |link:custommethods.adoc[Custom Methods]
|skip-constructor          |       |              |X           |              |             |link:immutable.adoc[Mapping immutable types]
|stop-on-errors            |X      |              |            |              |             |see below
|trim-strings              |X      |X             |            |              |             |see below
|type                      |       |X             |            |X             |             |link:oneway.adoc[One-Way Mapping]
|variables                 |X      |              |            |              |             |link:expressionlanguage.adoc[Expression Language]
|wildcard                  |X      |X             |            |              |             |see below
|wildcard-case-insensitive |X      |X             |            |              |             |see below
|===

==== 错误处理 (错误中停止 , 允许的异常)
缺省情况下，如果Dozer在处理域映射的时候遇到错误，将会抛出异常，并停止映射。
这是推荐的行为，Dozer可被指定为忽略异常，并继续进行下个域的映射，通过设定 `stop-on-errors` 策略。

你也可以设定哪些异常将导致Dozer停止或者重新抛出他们，即使 `stop-on-errors` 被设为 false, 仍可以使用 `allowed-exceptions` 元素:

[source,xml,prettyprint]
----
<configuration>
    <stop-on-errors>false</stop-on-errors>
    <allowed-exceptions>
        <exception>org.example.UnrecoverableError</exception>
        <exception>org.example.BadException</exception>
    </allowed-exceptions>
</configuration>
----

==== 整理字符串 (trim-strings)
正如名称所假设的，`trim-strings` 在调用目标对象的setter之前使用Java的 String.trim() 到源值上。

==== 通配符映射 (wildcard, wildcard-case-insensitive)
默认情况下，Dozer映射所有的在原始和目标对象之间映射所有相同的名称属性("wildcard mapping")。
在映射定义中罗列的属性将不会覆盖这个行为，只会排除这些属性。例如，给出如下的类

[source,java,prettyprint]
----
class Person {
    private String firstName;
    private String lastName;
}

class Contact {
    private String firstName;
    private String surname;
}
----

映射定义如下

[source,xml,prettyprint]
----
<mapping>
    <class-a>com.github.dozermapper.core.vo.Person</class-a>
    <class-b>com.github.dozermapper.core.vo.Contact</class-b>
    <field>
        <a>lastName</a>
        <b>surname</b>
    </field>
</mapping>
----

一个从`Person`对象到`Contact`对象的映射将会映射 `lastName` 到 `surname` 和 `firstName` 到 `firstName`,
即使后者没有在映射中被定义。

你可以全局上禁用通配符映射或者是在类映射级别上通过设定 `wildcard` 为 false。如果你这样做，你需要显示的设定每一队属性的映射:

[source,xml,prettyprint]
----
<mapping wildcard="false">
    <class-a>com.github.dozermapper.core.vo.Person</class-a>
    <class-b>com.github.dozermapper.core.vo.Contact</class-b>
    <field>
        <a>lastName</a>
        <b>surname</b>
    </field>
    <field>
        <a>firstName</a>
        <b>firstName</b>
        </field>
</mapping>
----

在Dozer 5.4.0版本之前, 通配符映射是大小写不敏感的。
当前版本的Dozer能够自动映射相同名字的属性。你可以通过设定`wildcard-case-insensitive`策略为true来启用旧的大小写不敏感的特性。
因此，例如一个源属性名称 `camelCase` 将被应用到目标属性 `camelcase`(以此类推)。
