== 配置
Dozer 配置属性可以通过一个可选的 Dozer 属性文件进行自定义。缺省情况，Dozer 将查看一个命名为dozer.properties的文件来载入配置属性。如果一个属性文件不能被找到或者被定义，缺省值将被使用。

Dozer 发布中包含一个例子dozer.properties 文件，将显示各种不同的选项。只需要把例子中的文件放到你的classpath，并自定义它。

一个额外的 Dozer 属性文件可以通过dozer.configuration system property. 等)进行定义，例如：
-Ddozer.configuration=someDozerConfigurationFile.properties

[cols="5*", options="header"]
.Dozer 配置属性
|===
|属性名称
|描述
|可用值
|缺省值
|

|dozer.el.enabled
|定义是否在XML 映射解析中Dozer 将识别EL 表达式。
|true
|false
|false

|dozer.cache.converter-by-dest-type-maxsize
|定义最大的一个内部Dozers缓存的大小
|0 - Long.MAX_VALUE
|10000
|

|dozer.cache.super-type-maxsize
|定义最大的一个内部Dozers缓存的大小
|0 - Long.MAX_VALUE
|10000
|

|dozer.beans.proxy-resolver-bean
|定义可被使用的 DozerProxyResolver 实现类
|正确的类名
|缺省的实现值
|

|dozer.beans.class-loader-bean
|定义可被使用的 DozerClassLoader 实现类
|正确的类名
|缺省的实现值
|
|=======================================================================

=== 调试初始化
一旦 Dozer 初始化信息可以被可选的发送到 System.out 来帮助调试。

为了启用这个附加的调试信息，可以设置 dozer.debug 系统属性。

ex) -Ddozer.debug=true

各种信息将被发送到System.out，包括载入的配置信息，自定xml的映射文件，版本信息，classloader 信息

[source,prettyprint]
----
dozer:  Trying to find Dozer configuration file: dozer.properties
dozer:  Using URL [file:/local/subversion_projects/dozer/trunk/target/test-classes/dozer.properties] for Dozer global property configuration
dozer:  Reading Dozer properties from URL [file:/local/subversion_projects/dozer/trunk/target/test-classes/dozer.properties]
dozer:  Finished configuring Dozer global properties
dozer:  Initializing Dozer.  Version: ${project.version}, Thread Name:main
dozer:  Initializing a new instance of the dozer bean mapper.
dozer:  Using the following xml files to load custom mappings for the bean mapper instance: [fieldAttributeMapping.xml]
dozer:  Trying to find xml mapping file: fieldAttributeMapping.xml
dozer:  Using URL [file:/local/subversion_projects/dozer/trunk/target/test-classes/fieldAttributeMapping.xml] to load custom xmlmappings
dozer:  Successfully loaded custom xml mappings from URL: [file:/local/subversion_projects/dozer/trunk/target/test-classes/fieldAttributeMapping.xml]
----
